<div class="objectcache:widget objectcache:groups-widget">
    <p>
        Run a cache scan to see a list of all groups currently present in the cache.
        This may take a while.
    </p>

    <div class="actions">
        <button class="button button-primary" data-text="Scan groups" data-loading="Scanning...">
            Scan groups
        </button>

        <button class="button button-secondary hidden" data-text="Copy groups" data-clipboard-target=".objectcache\:groups-widget .table-container">
            Copy to clipboard
        </button>

        <span class="success hidden" aria-hidden="true">Copied!</span>
    </div>
</div>
