
The object cache drop-in did not log any commands.
<br />
<br />
To enable logging set the <code>`save_commands`</code> or <code>`debug`</code> configuration option in your <code>`WP_REDIS_CONFIG`</code> to <code>true</code>.
<a href="https://objectcache.pro/docs/debugging" target="_blank">Read more...</a>
<br />
<br />
Command logging is automatically enabled when the <code>`SAVEQUERIES`</code> or <code>`WP_DEBUG`</code> constants are set to <code>true</code>.
